/**
 * Settings feature module public surface (NUMA-119 P5, PLAN 5.3 / 21.2).
 */
export * from "./settings.types"
export * from "./settings.api"
export * from "./settings.schema"
export * from "./settings.storage"
export * from "./settings.utils"
export * from "./settings.constants"

export { useAiSettings } from "./useAiSettings"
export type { UseAiSettingsReturn } from "./useAiSettings"
export { useCalendarConnection } from "./useCalendarConnection"
export type { UseCalendarConnectionReturn } from "./useCalendarConnection"
export { useSlackConnection } from "./useSlackConnection"
export type { UseSlackConnectionReturn } from "./useSlackConnection"
export { useTimelineSettings } from "./useTimelineSettings"
export type { UseTimelineSettingsReturn } from "./useTimelineSettings"
export { useIntegrationKeys } from "./useIntegrationKeys"
export type { UseIntegrationKeysReturn } from "./useIntegrationKeys"

export { AgentTogglePanel } from "./components/AgentTogglePanel"
export { AiProviderPanel } from "./components/AiProviderPanel"
export { AlertMessage } from "./components/AlertMessage"
export { ApiKeyField, OllamaUrlField } from "./components/ApiKeyField"
export { ConnectionStatusLine } from "./components/ConnectionStatusLine"
export { GoogleCalendarPanel } from "./components/GoogleCalendarPanel"
export { IntegrationGroupCard } from "./components/IntegrationGroupCard"
export { IntegrationKeyField } from "./components/IntegrationKeyField"
export { IntegrationKeysPanel } from "./components/IntegrationKeysPanel"
export { MealTimeFields } from "./components/MealTimeFields"
export { ModelSelect } from "./components/ModelSelect"
export { ProviderCardGrid } from "./components/ProviderCardGrid"
export { ProviderLogo } from "./components/ProviderLogo"
export { SecretInput } from "./components/SecretInput"
export { SettingsPageHeader } from "./components/SettingsPageHeader"
export { SettingsSection } from "./components/SettingsSection"
export { SlackPanel } from "./components/SlackPanel"
export { TemperatureSlider } from "./components/TemperatureSlider"
export { TimelinePanel } from "./components/TimelinePanel"
export { WaterReminderFields } from "./components/WaterReminderFields"
