"""baseline_schema

Revision ID: a1b2c3d4e5f6
Create Date: 2026-07-01

Baseline schema for NUMA. Captures the full table/trigger/function set that was
previously created by the inline TABLES DDL in src/core/db.py (NUMA-103).

Statements are the exact, idempotent (IF NOT EXISTS / OR REPLACE) DDL from that
list, in order, so this migration is a no-op on databases already bootstrapped by
the legacy init_db path and creates the full schema on a clean database. The four
pre-existing migrations now depend on this baseline.
"""
from alembic import op

revision = "a1b2c3d4e5f6"
down_revision = None
branch_labels = None
depends_on = None


# Exact statements copied from the legacy src/core/db.py TABLES list, in order.
STATEMENTS = [
    'CREATE EXTENSION IF NOT EXISTS pgcrypto',
    '\n    CREATE OR REPLACE FUNCTION public.set_updated_at()\n    RETURNS TRIGGER LANGUAGE plpgsql AS $$\n    BEGIN\n        NEW.updated_at = NOW();\n        RETURN NEW;\n    END;\n    $$\n    ',
    "\n    CREATE TABLE IF NOT EXISTS public.profiles (\n        id           UUID        PRIMARY KEY\n                                 REFERENCES auth.users(id) ON DELETE CASCADE,\n        full_name    TEXT,\n        avatar_url   TEXT,\n        google_id    TEXT,\n        timezone     TEXT        NOT NULL DEFAULT 'Asia/Kolkata',\n        created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()\n    )\n    ",
    'ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS google_id TEXT',
    "ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'Asia/Kolkata'",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_profiles_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_profiles_updated_at\n            BEFORE UPDATE ON public.profiles\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    "\n    CREATE TABLE IF NOT EXISTS public.tasks (\n        id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        title        TEXT        NOT NULL,\n        description  TEXT,\n        status       TEXT        NOT NULL DEFAULT 'planned'\n                                 CHECK (status IN ('planned', 'inprogress', 'completed', 'pending')),\n        priority     TEXT        CHECK (priority IN ('low', 'medium', 'high', 'urgent')),\n        due_date     TIMESTAMPTZ,\n        reminder_at  TIMESTAMPTZ,\n        source_name  TEXT,\n        source_logo  TEXT,\n        external_ref TEXT,\n        position     INTEGER     NOT NULL DEFAULT 0,\n        completed_at TIMESTAMPTZ,\n        created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()\n    )\n    ",
    'ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS external_ref TEXT',
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1\n            FROM pg_constraint\n            WHERE conname = 'uq_tasks_user_external_ref'\n              AND conrelid = 'public.tasks'::regclass\n        ) THEN\n            ALTER TABLE public.tasks\n            ADD CONSTRAINT uq_tasks_user_external_ref UNIQUE (user_id, external_ref);\n        END IF;\n    END $$\n    ",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_tasks_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_tasks_updated_at\n            BEFORE UPDATE ON public.tasks\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_tasks_user_status       ON public.tasks(user_id, status)',
    'CREATE INDEX IF NOT EXISTS idx_tasks_completed         ON public.tasks(user_id, completed_at) WHERE completed_at IS NOT NULL',
    'CREATE INDEX IF NOT EXISTS idx_tasks_user_external_ref ON public.tasks(user_id, external_ref)',
    "\n    CREATE TABLE IF NOT EXISTS public.cal_calendars (\n        id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        google_cal_id   TEXT        NOT NULL,\n        name            TEXT        NOT NULL,\n        access_role     TEXT        NOT NULL DEFAULT 'reader'\n                                    CHECK (access_role IN ('owner', 'writer', 'reader', 'freeBusyReader')),\n        is_primary      BOOLEAN     NOT NULL DEFAULT FALSE,\n        calendar_type   TEXT        NOT NULL DEFAULT 'personal'\n                                    CHECK (calendar_type IN ('personal', 'shared', 'holiday', 'birthday', 'other')),\n        sync_token      TEXT,\n        last_synced_at  TIMESTAMPTZ,\n        created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (user_id, google_cal_id)\n    )\n    ",
    "ALTER TABLE public.cal_calendars ADD COLUMN IF NOT EXISTS calendar_type TEXT NOT NULL DEFAULT 'personal'",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_cal_calendars_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_cal_calendars_updated_at\n            BEFORE UPDATE ON public.cal_calendars\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_cal_calendars_user         ON public.cal_calendars(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_cal_calendars_user_primary ON public.cal_calendars(user_id, is_primary)',
    "\n    CREATE TABLE IF NOT EXISTS public.cal_events (\n        id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        calendar_id         UUID        NOT NULL REFERENCES public.cal_calendars(id) ON DELETE CASCADE,\n        user_id             UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        google_event_id     TEXT        NOT NULL,\n        title               TEXT        NOT NULL DEFAULT '(No title)',\n        description         TEXT,\n        location            TEXT,\n        start_at            TIMESTAMPTZ NOT NULL,\n        end_at              TIMESTAMPTZ NOT NULL,\n        is_all_day          BOOLEAN     NOT NULL DEFAULT FALSE,\n        start_time_zone     TEXT,\n        end_time_zone       TEXT,\n        status              TEXT        NOT NULL DEFAULT 'confirmed'\n                                        CHECK (status IN ('confirmed', 'tentative', 'cancelled')),\n        etag                TEXT,\n        recurring_event_id  TEXT,\n        html_link           TEXT,\n        meet_link           TEXT,\n        organizer_email     TEXT,\n        organizer_name      TEXT,\n        is_readonly         BOOLEAN     NOT NULL DEFAULT FALSE,\n        deleted_at          TIMESTAMPTZ,\n        created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (calendar_id, google_event_id)\n    )\n    ",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_cal_events_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_cal_events_updated_at\n            BEFORE UPDATE ON public.cal_events\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_cal_events_user_start      ON public.cal_events(user_id, start_at)',
    'CREATE INDEX IF NOT EXISTS idx_cal_events_calendar_start  ON public.cal_events(calendar_id, start_at)',
    'CREATE INDEX IF NOT EXISTS idx_cal_events_active          ON public.cal_events(user_id, start_at) WHERE deleted_at IS NULL',
    'CREATE INDEX IF NOT EXISTS idx_cal_events_recurring       ON public.cal_events(recurring_event_id) WHERE recurring_event_id IS NOT NULL',
    "\n    CREATE TABLE IF NOT EXISTS public.cal_attendees (\n        id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        event_id        UUID        NOT NULL REFERENCES public.cal_events(id) ON DELETE CASCADE,\n        email           TEXT        NOT NULL,\n        display_name    TEXT,\n        response_status TEXT        NOT NULL DEFAULT 'needsAction'\n                                    CHECK (response_status IN ('needsAction', 'accepted', 'declined', 'tentative')),\n        is_organizer    BOOLEAN     NOT NULL DEFAULT FALSE,\n        is_self         BOOLEAN     NOT NULL DEFAULT FALSE,\n        optional        BOOLEAN     NOT NULL DEFAULT FALSE,\n        created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (event_id, email)\n    )\n    ",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_cal_attendees_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_cal_attendees_updated_at\n            BEFORE UPDATE ON public.cal_attendees\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_cal_attendees_event          ON public.cal_attendees(event_id)',
    'CREATE INDEX IF NOT EXISTS idx_cal_attendees_event_response ON public.cal_attendees(event_id, response_status)',
    "\n    CREATE TABLE IF NOT EXISTS public.cal_watch_channels (\n        id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id              UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        calendar_id          UUID        NOT NULL REFERENCES public.cal_calendars(id) ON DELETE CASCADE,\n        channel_uuid         TEXT        NOT NULL UNIQUE,\n        google_resource_id   TEXT,\n        status               TEXT        NOT NULL DEFAULT 'active'\n                                         CHECK (status IN ('active', 'expired', 'stopped')),\n        expires_at           TIMESTAMPTZ,\n        registered_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        last_notification_at TIMESTAMPTZ,\n        created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()\n    )\n    ",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_cal_watch_channels_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_cal_watch_channels_updated_at\n            BEFORE UPDATE ON public.cal_watch_channels\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_cal_watch_user       ON public.cal_watch_channels(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_cal_watch_calendar   ON public.cal_watch_channels(calendar_id)',
    'CREATE INDEX IF NOT EXISTS idx_cal_watch_status     ON public.cal_watch_channels(status)',
    "CREATE INDEX IF NOT EXISTS idx_cal_watch_expires_at ON public.cal_watch_channels(expires_at) WHERE status = 'active'",
    '\n    CREATE TABLE IF NOT EXISTS public.google_calendars (\n        id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id             UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        google_calendar_id  TEXT        NOT NULL,\n        summary             TEXT,\n        description         TEXT,\n        time_zone           TEXT,\n        access_role         TEXT,\n        selected            BOOLEAN     NOT NULL DEFAULT TRUE,\n        is_primary          BOOLEAN     NOT NULL DEFAULT FALSE,\n        raw_calendar        JSONB,\n        last_synced_at      TIMESTAMPTZ,\n        created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (user_id, google_calendar_id)\n    )\n    ',
    "\n    CREATE TABLE IF NOT EXISTS public.google_calendar_events (\n        id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id             UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        google_calendar_id  TEXT        NOT NULL,\n        google_event_id     TEXT        NOT NULL,\n        ical_uid            TEXT,\n        etag                TEXT,\n        sequence            INTEGER,\n        status              TEXT        CHECK (status IN ('confirmed', 'tentative', 'cancelled')),\n        summary             TEXT        NOT NULL DEFAULT '(No title)',\n        description         TEXT,\n        location            TEXT,\n        start_at            TIMESTAMPTZ NOT NULL,\n        end_at              TIMESTAMPTZ NOT NULL,\n        is_all_day          BOOLEAN     NOT NULL DEFAULT FALSE,\n        start_time_zone     TEXT,\n        end_time_zone       TEXT,\n        html_link           TEXT,\n        meet_link           TEXT,\n        organizer           JSONB,\n        creator             JSONB,\n        attendees           JSONB       NOT NULL DEFAULT '[]'::JSONB,\n        reminders           JSONB,\n        is_readonly         BOOLEAN     NOT NULL DEFAULT FALSE,\n        deleted_at          TIMESTAMPTZ,\n        created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (user_id, google_calendar_id, google_event_id)\n    )\n    ",
    "\n    DO $$ BEGIN\n        IF EXISTS (\n            SELECT 1 FROM information_schema.columns\n            WHERE table_schema = 'public'\n              AND table_name   = 'google_calendar_events'\n              AND column_name  = 'raw_event'\n        ) THEN\n            ALTER TABLE public.google_calendar_events DROP COLUMN raw_event;\n        END IF;\n    END $$\n    ",
    "\n    CREATE TABLE IF NOT EXISTS public.google_calendar_sync_state (\n        id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id                UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        sync_scope             TEXT        NOT NULL DEFAULT 'incremental'\n                                    CHECK (sync_scope IN ('full', 'incremental', 'watch')),\n        next_sync_token        TEXT,\n        last_sync_started_at   TIMESTAMPTZ,\n        last_sync_completed_at TIMESTAMPTZ,\n        last_sync_status       TEXT        CHECK (last_sync_status IN ('success', 'failed', 'running')),\n        last_sync_error        TEXT,\n        watch_channel_id       TEXT,\n        watch_resource_id      TEXT,\n        watch_expiration       TIMESTAMPTZ,\n        watch_message_number   BIGINT,\n        created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (user_id)\n    )\n    ",
    '\n    CREATE TABLE IF NOT EXISTS public.slack_channels (\n        id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        slack_id      TEXT        NOT NULL UNIQUE,\n        name          TEXT,\n        team_id       TEXT        NOT NULL,\n        is_private    BOOLEAN     NOT NULL DEFAULT FALSE,\n        created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()\n    )\n    ',
    'CREATE INDEX IF NOT EXISTS idx_slack_channels_slack_id ON public.slack_channels(slack_id)',
    'CREATE INDEX IF NOT EXISTS idx_slack_channels_team_id  ON public.slack_channels(team_id)',
    "\n    CREATE TABLE IF NOT EXISTS public.slack_messages (\n        id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id          UUID        REFERENCES auth.users(id) ON DELETE SET NULL,\n        slack_user_id    TEXT        NOT NULL,\n        slack_team_id    TEXT        NOT NULL,\n        channel_id       UUID        REFERENCES public.slack_channels(id) ON DELETE SET NULL,\n        slack_channel_id TEXT        NOT NULL,\n        channel_name     TEXT,\n        text             TEXT,\n        ts               TEXT        NOT NULL UNIQUE,\n        thread_ts        TEXT,\n        message_type     TEXT        NOT NULL DEFAULT 'message',\n        raw_payload      JSONB,\n        created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()\n    )\n    ",
    'CREATE INDEX IF NOT EXISTS idx_slack_messages_user       ON public.slack_messages(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_slack_messages_created_at ON public.slack_messages(created_at DESC)',
    'CREATE INDEX IF NOT EXISTS idx_slack_messages_channel    ON public.slack_messages(slack_channel_id)',
    'CREATE INDEX IF NOT EXISTS idx_slack_messages_ts         ON public.slack_messages(ts)',
    '\n    CREATE TABLE IF NOT EXISTS public.slack_auth (\n        id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id         UUID        NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,\n        slack_user_id   TEXT        NOT NULL,\n        slack_team_id   TEXT        NOT NULL,\n        access_token    TEXT        NOT NULL,\n        bot_token       TEXT,\n        team_name       TEXT,\n        authed_user_obj JSONB,\n        created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()\n    )\n    ',
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_slack_auth_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_slack_auth_updated_at\n            BEFORE UPDATE ON public.slack_auth\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_slack_auth_user_id ON public.slack_auth(user_id)',
    "\n    CREATE TABLE IF NOT EXISTS public.health_snapshots (\n        id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        source          TEXT        NOT NULL CHECK (source IN ('google_fit', 'strava')),\n        snapshot_date   DATE        NOT NULL,\n        steps           INTEGER,\n        active_minutes  INTEGER,\n        calories        INTEGER,\n        distance_km     REAL,\n        sleep_hours     REAL,\n        heart_rate_bpm  REAL,\n        heart_points    REAL,\n        sleep_start_at  TIMESTAMPTZ,\n        sleep_end_at    TIMESTAMPTZ,\n        sleep_stages    JSONB,\n        sleep_segments  JSONB,\n        activities      JSONB,\n        raw_data        JSONB,\n        created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (user_id, source, snapshot_date)\n    )\n    ",
    'ALTER TABLE public.health_snapshots ADD COLUMN IF NOT EXISTS heart_rate_bpm REAL',
    'ALTER TABLE public.health_snapshots ADD COLUMN IF NOT EXISTS heart_points REAL',
    'ALTER TABLE public.health_snapshots ADD COLUMN IF NOT EXISTS sleep_start_at TIMESTAMPTZ',
    'ALTER TABLE public.health_snapshots ADD COLUMN IF NOT EXISTS sleep_end_at TIMESTAMPTZ',
    'ALTER TABLE public.health_snapshots ADD COLUMN IF NOT EXISTS sleep_segments JSONB',
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_health_snapshots_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_health_snapshots_updated_at\n            BEFORE UPDATE ON public.health_snapshots\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_health_snapshots_user_date   ON public.health_snapshots(user_id, snapshot_date DESC)',
    'CREATE INDEX IF NOT EXISTS idx_health_snapshots_user_source ON public.health_snapshots(user_id, source, snapshot_date DESC)',
    "\n    CREATE TABLE IF NOT EXISTS public.health_intraday_snapshots (\n        id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        source          TEXT        NOT NULL CHECK (source IN ('google_fit', 'strava')),\n        snapshot_date   DATE        NOT NULL,\n        window_start_at TIMESTAMPTZ NOT NULL,\n        window_end_at   TIMESTAMPTZ NOT NULL,\n        bucket_minutes  INTEGER     NOT NULL DEFAULT 60,\n        steps           INTEGER     NOT NULL DEFAULT 0,\n        calories        INTEGER     NOT NULL DEFAULT 0,\n        distance_km     REAL        NOT NULL DEFAULT 0,\n        buckets         JSONB       NOT NULL DEFAULT '[]'::JSONB,\n        created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (user_id, source, snapshot_date, bucket_minutes)\n    )\n    ",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_health_intraday_snapshots_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_health_intraday_snapshots_updated_at\n            BEFORE UPDATE ON public.health_intraday_snapshots\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_health_intraday_user_date ON public.health_intraday_snapshots(user_id, snapshot_date DESC)',
    "\n    CREATE TABLE IF NOT EXISTS public.user_ai_settings (\n        id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id           UUID        NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,\n        provider          TEXT        NOT NULL DEFAULT 'groq'\n                                      CHECK (provider IN ('groq', 'openai', 'anthropic', 'gemini', 'ollama')),\n        model_id          TEXT        NOT NULL DEFAULT 'llama-3.3-70b-versatile',\n        encrypted_api_key TEXT,\n        ollama_base_url   TEXT        DEFAULT 'http://localhost:11434',\n        temperature       REAL        NOT NULL DEFAULT 0.1,\n        created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()\n    )\n    ",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_user_ai_settings_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_user_ai_settings_updated_at\n            BEFORE UPDATE ON public.user_ai_settings\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_user_ai_settings_user ON public.user_ai_settings(user_id)',
    "\n    CREATE TABLE IF NOT EXISTS public.journal_entries (\n        id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id     UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        title       TEXT        NOT NULL DEFAULT '',\n        content     TEXT        NOT NULL DEFAULT '',\n        mood        TEXT        CHECK (mood IN ('great', 'good', 'okay', 'bad', 'terrible')),\n        entry_date  DATE        NOT NULL DEFAULT CURRENT_DATE,\n        tags        TEXT[]      DEFAULT '{}',\n        ai_summary  TEXT,\n        created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (user_id, entry_date)\n    )\n    ",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_journal_entries_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_journal_entries_updated_at\n            BEFORE UPDATE ON public.journal_entries\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_journal_entries_user_date ON public.journal_entries(user_id, entry_date DESC)',
    "\n    CREATE TABLE IF NOT EXISTS public.github_auth (\n        id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id          UUID        NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,\n        github_username  TEXT        NOT NULL,\n        github_user_id   INTEGER     NOT NULL,\n        access_token     TEXT        NOT NULL,\n        scope            TEXT,\n        token_source     TEXT,\n        token_permissions JSONB      NOT NULL DEFAULT '{}'::JSONB,\n        token_last_verified_at TIMESTAMPTZ,\n        token_expires_at TIMESTAMPTZ,\n        avatar_url       TEXT,\n        created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()\n    )\n    ",
    'ALTER TABLE public.github_auth ADD COLUMN IF NOT EXISTS token_source TEXT',
    "ALTER TABLE public.github_auth ADD COLUMN IF NOT EXISTS token_permissions JSONB NOT NULL DEFAULT '{}'::JSONB",
    'ALTER TABLE public.github_auth ADD COLUMN IF NOT EXISTS token_last_verified_at TIMESTAMPTZ',
    'ALTER TABLE public.github_auth ADD COLUMN IF NOT EXISTS token_expires_at TIMESTAMPTZ',
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_github_auth_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_github_auth_updated_at\n            BEFORE UPDATE ON public.github_auth\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_github_auth_user_id ON public.github_auth(user_id)',
    "\n    CREATE TABLE IF NOT EXISTS public.github_repositories (\n        id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        github_repo_id  BIGINT,\n        name            TEXT        NOT NULL,\n        full_name       TEXT        NOT NULL,\n        owner_login     TEXT,\n        private         BOOLEAN     NOT NULL DEFAULT FALSE,\n        fork            BOOLEAN     NOT NULL DEFAULT FALSE,\n        archived        BOOLEAN     NOT NULL DEFAULT FALSE,\n        disabled        BOOLEAN     NOT NULL DEFAULT FALSE,\n        language        TEXT,\n        stars           INTEGER     NOT NULL DEFAULT 0,\n        forks           INTEGER     NOT NULL DEFAULT 0,\n        open_issues     INTEGER     NOT NULL DEFAULT 0,\n        default_branch  TEXT,\n        html_url        TEXT,\n        clone_url       TEXT,\n        pushed_at       TIMESTAMPTZ,\n        updated_at_api  TIMESTAMPTZ,\n        permissions     JSONB       NOT NULL DEFAULT '{}'::JSONB,\n        raw_payload     JSONB       NOT NULL DEFAULT '{}'::JSONB,\n        last_synced_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (user_id, full_name)\n    )\n    ",
    "\n    CREATE TABLE IF NOT EXISTS public.github_commits (\n        id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        repo_full_name  TEXT        NOT NULL,\n        sha             TEXT        NOT NULL,\n        message         TEXT        NOT NULL DEFAULT '',\n        author_name     TEXT,\n        author_email    TEXT,\n        author_login    TEXT,\n        committed_at    TIMESTAMPTZ,\n        html_url        TEXT,\n        raw_payload     JSONB       NOT NULL DEFAULT '{}'::JSONB,\n        last_synced_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (user_id, repo_full_name, sha)\n    )\n    ",
    "\n    CREATE TABLE IF NOT EXISTS public.github_resource_snapshots (\n        id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n        user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,\n        repo_full_name  TEXT,\n        resource_type   TEXT        NOT NULL CHECK (\n            resource_type IN (\n                'pull_request',\n                'issue',\n                'action_run',\n                'commit_status',\n                'deployment',\n                'discussion',\n                'environment',\n                'package',\n                'page',\n                'project',\n                'security_event',\n                'webhook'\n            )\n        ),\n        external_id     TEXT        NOT NULL,\n        title           TEXT,\n        state           TEXT,\n        html_url        TEXT,\n        occurred_at     TIMESTAMPTZ,\n        raw_payload     JSONB       NOT NULL DEFAULT '{}'::JSONB,\n        last_synced_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n        UNIQUE (user_id, resource_type, external_id)\n    )\n    ",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_github_repositories_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_github_repositories_updated_at\n            BEFORE UPDATE ON public.github_repositories\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_github_commits_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_github_commits_updated_at\n            BEFORE UPDATE ON public.github_commits\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    "\n    DO $$ BEGIN\n        IF NOT EXISTS (\n            SELECT 1 FROM pg_trigger\n            WHERE tgname = 'trg_github_resource_snapshots_updated_at'\n        ) THEN\n            CREATE TRIGGER trg_github_resource_snapshots_updated_at\n            BEFORE UPDATE ON public.github_resource_snapshots\n            FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();\n        END IF;\n    END $$\n    ",
    'CREATE INDEX IF NOT EXISTS idx_github_repos_user_private ON public.github_repositories(user_id, private)',
    'CREATE INDEX IF NOT EXISTS idx_github_repos_user_pushed ON public.github_repositories(user_id, pushed_at DESC)',
    'CREATE INDEX IF NOT EXISTS idx_github_commits_user_time ON public.github_commits(user_id, committed_at DESC)',
    'CREATE INDEX IF NOT EXISTS idx_github_commits_repo_time ON public.github_commits(user_id, repo_full_name, committed_at DESC)',
    'CREATE INDEX IF NOT EXISTS idx_github_resources_user_type_time ON public.github_resource_snapshots(user_id, resource_type, occurred_at DESC)',
]


def upgrade() -> None:
    for stmt in STATEMENTS:
        op.execute(stmt)


def downgrade() -> None:
    # Baseline schema is not reversible; a downgrade would drop all app data.
    raise NotImplementedError("Downgrade past the baseline schema is not supported.")
